services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - website
      - cadvisor
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - ./requirements/nginx/ssl:/etc/nginx/ssl
      - wordpress_data:/var/www/html
      - website_content:/var/www/bonus
    networks:
      - inception-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -k https://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
      - redis
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-net
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep 'php-fpm' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    build: ./requirements/bonus/redis_cache
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - inception-net
    expose:
      - 6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  ftp:
    build: ./requirements/bonus/ftp_server
    container_name: ftp
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep vsftpd || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
     
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception-net
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    
  website:
    build: ./requirements/bonus/website
    container_name: website
    restart: always
    networks:
      - inception-net
    volumes:
      - website_content:/website
    healthcheck:
      test: ["CMD-SHELL", "test -f /website/index.html || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - inception-net
    privileged: true
    pid: "host"
    restart: always
    security_opt:
      - apparmor=unconfined
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/redis
      o: bind
  website_content:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/website
      o: bind

networks:
  inception-net:
    name: 42inception_inception-net
    driver: bridge
